### ISSUE TITLE
Parser Error: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-api#100]
> url: https://feeds.blubrry.com/feeds/albumepitaph.xml
> 
> feedUrlId: VLO4NBqD0D
> 
> errorMessage: Cannot read property 'forEach' of undefined

**Comment by mitchdowney** [comment]
I think this should be fixed in https://github.com/podverse/podcast-feed-parser/commit/b55a7a90af3714fb31bcbd1fe15a48592ab8a57b
