### ISSUE TITLE
Broken Podcast Images

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-api#121]
This is an ongoing list of podcasts with broken images on Podverse.

Search podcasts: Darker Projects

**Comment by mitchdowney** [comment]
There are so many broken podcast images in the open podcast ecosystem, that I think rather than keep an ongoing list of broken podcast images, we'll fix images as errors are reported by users. Otherwise the vast majority we try to fix will be actually broken images and not our server's fault.
