### ISSUE TITLE
Request Data Extract for Specific tables

### ISSUE THREAD

**Issue by Trolladactyl** [podverse/podverse-api#583]
Hi @mitchdowney and @suorcdm,  Can you supply or show me how to pull down values from production for the following tables?

Public.Episodes
Public.Playlists
Public.Podcasts
Public.QueueItems
Public.MediaRefs
Public.Categories

I think that will be fine for now.

**Comment by mitchdowney** [comment]
I was going to use the QA populate database scripts for things like this. Are there any reasons they won't work for your purposes? Happy to make those scripts a top priority.

**Comment by Trolladactyl** [comment]
They will work to get a general idea of the performance.

**Comment by mitchdowney** [comment]
These should have already been available in the Sandbox DB:

Public.Categories
Public.Podcasts
Public.Episodes
Public.MediaRefs

If you're not seeing those, let me know.

And I just added the following to our Sandbox DB seed script, and added them to the Sandbox DB:

Public.Playlists
Public.QueueItems

https://github.com/podverse/podverse-api/pull/589/files

**Comment by suorcd** [comment]
Closing issue, it has been over a year.
