### ISSUE TITLE
Keep The Search Bar From Scrolling

### ISSUE THREAD

**Issue by Trolladactyl** [podverse/podverse-api#585]
When Searching podcasts the search bar will scroll off the top of the screen. Can it be locked on the screen?

**Comment by mitchdowney** [comment]
@Trolladactyl is this for the mobile app or the website?

Mobile app repo: https://github.com/podverse/podverse-rn

Web app repo: https://github.com/podverse/podverse-web

**Comment by Trolladactyl** [comment]
This is for the Mobile app.

**Comment by mitchdowney** [comment]
@Trolladactyl I just created a copy of this issue in podverse-rn. I'll close the issue here.

https://github.com/podverse/podverse-rn/issues/1607
