### ISSUE TITLE
"!" exclamation mark breaks Search

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-api#635]
![image](https://github.com/podverse/podverse-api/assets/31670210/3aedeb2a-5fd2-43c6-816d-fce5726db107)
![image](https://github.com/podverse/podverse-api/assets/31670210/4b727234-7591-47cb-8e85-ef62ebbb0bc2)

**Comment by mitchdowney** [comment]
This should be in v4.13.8 https://github.com/podverse/podverse-api/pull/650
