### ISSUE TITLE
Update Github action to post to the alerts room on start and finish of deploy

### ISSUE THREAD

**Issue by suorcd** [podverse/podverse-api#680]
Update Github action to post to the matrix alerts room on start and finish of deploy

This will require a 
- new bot user
- user access token
- room ID

The bot user will need to be invited to the matrix room
We will need updates to the org for org wide variables

And then update the GH actions to incorporate https://github.com/marketplace/actions/matrix-message

**Comment by mitchdowney** [comment]
@suorcd and I updated the master.yml files to include posting notifications to our Alerts Matrix room. If there are more steps that I'm missing, feel free to reopen it.
