### ISSUE TITLE
Truncate episode description

### ISSUE THREAD

**Issue by suorcd** [podverse/podverse-api#746]
Seems like the standard is to parse 4000 characters of a description.
While this can make for an awkward transition in a sentence that is a huge column.

The parser would need to be updated

Then we'd need to go back thru the column and truncate.
Or create a new column and move the data over.

**Comment by mitchdowney** [comment]
This should be in v4.16.14

https://github.com/podverse/podverse-api/pull/734/commits/30fa7513eac1c02b9dbff465e2ff73558834b609
