### ISSUE TITLE
Parser Error: Cannot read property 'channel' of undefined

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-api#97]
> url: http://feeds.feedburner.com/http/theselfsufficientwaycom/feedpodcast
> 
> feedUrlId: wd2bzsnLB-
> 
> errorMessage: Cannot read property 'channel' of undefined

**Comment by mitchdowney** [comment]
This feedUrl is currently a dead link. I think I'm just going to ignore these types of failures, since our integration with the Podcast Index should prevent us from excessively re-parsing dead feeds.
