### ISSUE TITLE
Parser Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-api#98]
> url: http://rctodayshow.com/feed/podcast/
> 
> feedUrlId: LgGBRm3RdA
> 
> errorMessage: Cannot read property 'length' of undefined

**Comment by mitchdowney** [comment]
I can no longer reproduce this issue. I believe the error was fixed in this commit https://github.com/podverse/podverse-api/commit/a4acfd8df580e525a88253617289b2a434a9dc5b
