### ISSUE TITLE
Parser Error: Cannot read property '0' of null

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-api#99]
> url: https://feeds.blubrry.com/feeds/albumepitaph.xml
> 
> feedUrlId: VLO4NBqD0D
> 
> errorMessage: Cannot read property '0' of null

**Comment by mitchdowney** [comment]
This feed was throwing a `cannot forEach of undefined` error last I checked, so I think this should be fixed in https://github.com/podverse/podcast-feed-parser/commit/b55a7a90af3714fb31bcbd1fe15a48592ab8a57b
